apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-nfs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      role: test-nfs-server
  template:
    metadata:
      labels:
        role: test-nfs-server
    spec:
      containers:
      - name: test-nfs-server
#        image: cloudgenius/nfs-server:4.1
        image: cloudgenius/nfs-server:test
#        image: gcr.io/cloudgeniuslabs/github-beacloudgenius-k8s-stack:f034ee686b78de9f898cf2378fa8589248373b88
        imagePullPolicy: Always
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: mypvc
      volumes:
        - name: mypvc
          gcePersistentDisk:
            pdName: somedisk
            fsType: ext4
