# This mounts the nfs volume claim into /mnt and continuously
# overwrites /mnt/index.html with the time and hostname of the pod.

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tcs
spec:
  replicas: 1
  selector:
    matchLabels:
      role: tcs
  template:
    metadata:
      labels:
        role: tcs
    spec:
      containers:
      - image: cloudgenius/wordpress:4.9.1
        imagePullPolicy: IfNotPresent
        name: tcs
        # resources:
        #   requests:
        #     cpu: "300m"
        #     memory: "512Mi"
        #   limits:
        #     cpu: "300m"
        #     memory: "512Mi"
        volumeMounts:
          # name must match the volume name below
          - name: my-pvc-nfs
            mountPath: "/var/www/html/"
      volumes:
      - name: my-pvc-nfs
        persistentVolumeClaim:
          claimName: tcs
