apiVersion: v1
kind: PersistentVolume
metadata:
  name: busy
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: poorman-nfs.default.svc.cluster.local
    path: "/busy"
---
apiVersion: v1
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: busy
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
