# This mounts the nfs volume claim into /mnt and continuously
# overwrites /mnt/index.html with the time and hostname of the pod.

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: busy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: busy
  template:
    metadata:
      labels:
        name: busy
    spec:
      containers:
      - image: busybox
        command:
          - sh
          - -c
          - 'while true; do date > /mnt/busy.html; hostname >> /mnt/busy.html; sleep $(($RANDOM % 5 + 5)); done'
        imagePullPolicy: IfNotPresent
        name: busybox
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "50m"
            memory: "128Mi"
        volumeMounts:
          # name must match the volume name below
          - name: my-pvc-nfs
            mountPath: "/mnt"
      volumes:
      - name: my-pvc-nfs
        persistentVolumeClaim:
          claimName: busy
